from enum import Enum


class ErrorEnum(Enum):
    """The ErrorEnum class specifies
    the concept of the error generated.
    Can be used with Global Error or
    Device Error Responses."""

    DEVICE_DELETED = 'DEVICE-DELETED'
    RESOURCE_CONSTRAINT_VIOLATION = 'RESOURCE-CONSTRAINT-VIOLATION'
    DEVICE_UNAVAILABLE = 'DEVICE-UNAVAILABLE'
    CAPABILITY_NOT_SUPPORTED = 'CAPABILITY-NOT-SUPPORTED'
    TOKEN_EXPIRED = 'TOKEN-EXPIRED'
    INTEGRATION_DELETED = 'INTEGRATION-DELETED'
    BAD_REQUEST = 'BAD-REQUEST'
    INVALID_TOKEN = 'INVALID-TOKEN'
    INVALID_INTERACTION_TYPE = 'INVALID-INTERACTION-TYPE'
    UNSUPPORTED_GRANT_TYPE = 'UNSUPPORTED-GRANT-TYPE'
    INVALID_CODE = 'INVALID-CODE'
    INVALID_CLIENT_SECRET = 'INVALID-CLIENT-SECRET'
    INVALID_CLIENT = 'INVALID-CLIENT'
